Feat/#4
AgID/spid-oidc-check-op pull request #9
Opened 2023-03-13 10:29 UTC by FedericoFanara92

fix: #4

2023-03-13 14:48 UTC, FedericoFanara92 commented
La PR contiene solamente il primo subset di 21 Unit Test realizzati e verificati

2023-03-26 16:21 UTC, damikael requested changes

2023-03-26 16:21 UTC, damikael commented on src/test/1.2.2.js
> +    this.notes = JSON.parse(
per recuperare il contenuto del jwt utilizzare jwt_decode

2023-03-26 16:21 UTC, damikael commented on src/test/1.2.2.js
> +    if (this.notes.alg == null || this.notes.alg == undefined)
non fa parte di questo test, spostare nel test di firma (1.2.4)

2023-03-26 16:21 UTC, damikael commented on src/test/1.2.3.js
> +      !response.headers["content-type"].includes(
non includes, deve essere uguale a 'application/entity-statement+jwt'

2023-03-26 16:21 UTC, damikael commented on src/test/1.2.4.js
> +    await keystore.add(private_key, 'pem');
sbagliato, occorre verificare la firma con la chiave pubblica presa da jwks o signed_jwks_uri

2023-03-26 16:21 UTC, damikael commented on src/test/1.2.7.js
> +    if ((this.document.iss !== this.document.sub) == null) {
?
dovrebbe essere
if (this.document.iss !== this.document.sub) {

2023-03-26 16:21 UTC, damikael commented on src/test/1.4.0.js
> +    this.validation = 'automatic';
impostare come self, così che l'utente può valutare personalmente se inserirlo o meno

2023-03-26 16:21 UTC, damikael commented on src/test/1.4.11.js
> +    this.validation = "automatic";
self

2023-03-26 16:21 UTC, damikael commented on src/test/1.4.12.js
> +    this.validation = "automatic";
self

2023-03-26 16:21 UTC, damikael commented on src/test/1.4.2.js
> +    this.validation = 'automatic';
self

2023-03-26 16:21 UTC, damikael commented on src/test/1.4.6.js
> +    this.validation = "automatic";
self

2023-03-26 16:21 UTC, damikael commented on src/test/1.4.7.js
> +    this.validation = "automatic";
self

2023-03-26 16:21 UTC, damikael commented on src/test/1.4.9.js
> +    this.validation = "automatic";
self

2023-04-04 17:40 UTC, damikael commented on src/test/1.2.2.js
> +    this.notes = JSON.parse(
ok, risolto

2023-04-04 17:42 UTC, damikael commented on src/test/1.2.2.js
> +    if (this.notes.alg == null || this.notes.alg == undefined)
ok, risolto

2023-04-04 17:42 UTC, damikael commented on src/test/1.2.3.js
> +      !response.headers["content-type"].includes(
ok, risolto

2023-04-04 17:44 UTC, damikael commented on src/test/1.2.4.js
> +    await keystore.add(private_key, 'pem');
da testare, cmq ok risolto

2023-04-04 17:45 UTC, damikael commented on src/test/1.4.0.js
> +    this.validation = 'automatic';
ok

2023-04-04 17:45 UTC, damikael commented on src/test/1.4.12.js
> +    this.validation = "automatic";
ok

2023-04-04 17:45 UTC, damikael commented on src/test/1.4.11.js
> +    this.validation = "automatic";
ok

2023-04-04 17:46 UTC, damikael commented on src/test/1.4.2.js
> +    this.validation = 'automatic';
ok

2023-04-04 17:46 UTC, damikael commented on src/test/1.4.6.js
> +    this.validation = "automatic";
ok

2023-04-04 17:46 UTC, damikael commented on src/test/1.4.7.js
> +    this.validation = "automatic";
ok

2023-04-04 17:46 UTC, damikael commented on src/test/1.4.9.js
> +    this.validation = "automatic";
ok

2023-04-04 17:48 UTC, merged

2023-05-09 16:55 UTC, damikael commented on src/test/1.2.4.js
> +    this.notes(returnedDocumentVerified);
this.notes is not a function